index.html
wordbank.html

add start code to index & word bank html

add code to html file

---

assets/js/script.js
assets/js/wordbank.js
wordbank.html

Added Pseudocode to both JS files and wordbank html file

---

assets/js/script.js

add function generate random number

---

assets/js/script.js

Added number generator function

Number generator

---

assets/css/style.css
index.html

Added bootstrap styles to index.html - divided homepage and gameplay sections for easy future display values

added bootstrap styles to index.html

---

assets/js/script.js
index.html

merged random number and random word generator and added click to start andword bank button

Merged Random number and word generators

---

assets/css/style.css
assets/js/script.js
assets/js/wordbank.js
index.html
wordbank.html

- Added wordbank modal to wordbank.html
- Added function to pull word button from stored array of words (will be used to grab from local storage). And added styling to word buttons (wordbank.js)
- Added event listener to show modal on each word button click - with unique information on each button (wordbank.js)
- Added class button-footer to index.html and wordbank.html to fix buttons to bottom of the main element

Feature wordbank modal

---

assets/js/script.js
assets/js/wordbank.js
wordbank.html

Added button to remove banked word
Changed random word generator
Changed logic to repeat call if number is wrong length.
Added array for in game hints

Remove banked word

---

assets/js/script.js

Set local storage to store all generated words on page refresh

Feature local storage wordbank

---

assets/js/script.js
assets/js/wordbank.js

Added or  operator to load storage function to account for empty array of local Storage

adjusted local storage setItems to || []

---

assets/js/script.js
assets/js/wordbank.js
wordbank.html

Set up retrieve of data on wordbank page
- populate modals with data from storage

retrieve storage on wordbank page and populate data to word modals

---

assets/js/script.js
index.html

Added start button function and screen switch.

Start game

---

assets/css/style.css
assets/js/script.js
index.html

add gamplay code 

---

assets/css/style.css
assets/js/script.js
assets/js/wordbank.js
index.html
wordbank.html

- Added Bootstrap styles throughout page - for group review on look and feel
- Created function to calculate score and hold in local storage
- Added Bulma stats bar to word bank - value will be pulled from local stored score

Feature styles

---

assets/css/style.css
assets/js/script.js
assets/js/wordbank.js
index.html

Added delete button
Added next hint function
Merged with Amy's updates

Delete btn gameplay

---

assets/js/script.js
index.html

comment out the word blanks /// update the common letters in an array

handle wordguess 

---

assets/css/style.css
assets/js/script.js
assets/js/wordbank.js
wordbank.html

- Wrod Wrap of Modal Text
- Handle hint presenetation on requests

Feature wordbankmodal styles

---

assets/css/style.css
assets/js/script.js
assets/js/wordbank.js
index.html

- Adjusted styling and alerts during final guesses
- Buges still to fix: warning button replace

Feature winlose

---

assets/js/script.js
index.html

as well as filler text showing up then disappearing

Fixed timeout and first hint being shown

---

assets/css/style.css
assets/js/script.js
assets/js/wordbank.js
index.html
wordbank.html

- Fixed localStorage score function
- Added math to calculate percents of wins and losses and show on progress bar
- Adjust html bootstrap styling on home page - and wordbank page 
- Added details to home page (game play definition etc.)
- Added CSS media query to adjust game title size for smaller screens

Feature localstoredscores

---

assets/css/style.css
assets/js/script.js
assets/js/wordbank.js
index.html
wordbank.html

Made updates from our meeting, including:
- Clear letterbank on each game play
- Responsive gameplay buttons (for smaller screens)
- Removed loss stats bar
- Updated input alert to reflect length of random word
- Added Dictionary Link to wordbank-modals
- Adjusted synonyms in wordbank modal to be more spaced in string
- Added logic to look for word between 5-7 characters long

Feature gameplay

---

assets/css/style.css
assets/js/wordbank.js
index.html
wordbank.html

Small adjustments:
- Home button on wordbank.html now works
- Wordbank button on game play page has consistent styles with other buttons
- Adjust guessed words styles with letter spacing - and top-padding to differentiate form letter output.

Feature - Styles Update

---

assets/css/style.css
assets/js/script.js
index.html
wordbank.html

Made the wordbank container stretchy
Changed hint font
Added error for failed connection
Moved subtitle to centre
Input not visible till game is ready
Mobile friendly CSS

Wordlength

---

assets/css/style.css
assets/js/script.js

- changed display of bankEl on game start

Letterboxdisplay

---

assets/js/script.js

guessed words array refreshing on game start

---

README.md
assets/css/style.css
assets/js/wordbank.js
index.html
wordbank.html

- Reviewed README file with minor edits
- Adjusted position of stats bar on wordbank
- Corrected wordbank header on wordbank page

Feature readme
